# This workflow will install Python dependencies
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Add action-runner deploy keys
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
         mkdir -p /home/runner/.ssh
         ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
         # PYNE_SSH_KEY is the name of the repository secret
         echo "${{ secrets.PYNE_SSH_KEY }}" > /home/runner/.ssh/pyne_github_runner
         chmod 600 /home/runner/.ssh/pyne_github_runner
         ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
         ssh-add /home/runner/.ssh/pyne_github_runner
    
    - name: Install dependencies
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv run setup
        sudo apt install ffmpeg
    - name: Test with pyne
      run: |
        pipenv run tests
